### ISSUE TITLE
[Mod Request] Noisium

### ISSUE THREAD

**Issue by Uranite** [intergrav/Adrenaserver#6]
Modrinth link:
https://modrinth.com/mod/noisium

Github link:
https://github.com/Steveplays28/noisium

> Optimises worldgen performance for a better gameplay experience.
> 
> The improvements lie between a 20-30% speedup when generating new chunks in vanilla Minecraft (benchmarked on 1.20.1 Fabric).

**Comment by getchoo** [comment]
this looks interesting, but i would be hesitant to add it just yet after seeing https://github.com/Steveplays28/noisium/issues/16 and https://github.com/Steveplays28/noisium/issues/10.

i'll keep this open for now though - to come back when these issues are hopefully closed

**Comment by Steveplays28** [comment]
Hi, FYI, I've added compatibility for Lithium on my end in [`v2.0.2`](https://github.com/Steveplays28/noisium/releases/latest), which fixes those issues.
Thanks for checking out Noisium.
